sudo: false
language: scala
dist: bionic
jdk:
- openjdk11
before_install:
- export CXX='g++-4.8'
- nvm install 10.13.0 && nvm use 10.13.0 && npm install
- wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | python -c "import sys; main=lambda x,y:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main('~/calibre-bin', True)" >/dev/null
- export PATH="~/calibre-bin/calibre/:/home/travis/calibre-bin/calibre/:$PATH"
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
  - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - graphviz
    - tree
script:
- sbt scalazDiagram build epub
- git checkout .
- mv gitbook/_book ../
- mv book.epub ../_book/scalaz-docs.epub
after_success:
- echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy.key\n"
  >> ~/.ssh/config
- openssl aes-256-cbc -pass "pass:$SERVER_KEY" -pbkdf2 -in ./.travis/deploy_key.enc
  -d -a -out deploy.key
- cp deploy.key ~/.ssh/
- chmod 600 ~/.ssh/deploy.key
- git config --global user.email "6b656e6a69@gmail.com"
- git config --global user.name "xuwei-k"
- git fetch origin gh-pages:gh-pages && git clean -fdx &&
  git checkout gh-pages && rm -rf ./* && cp -r ../_book/* ./ && git add . && git commit
  -a -m "auto commit on travis $TRAVIS_JOB_NUMBER $TRAVIS_COMMIT ${TRAVIS_COMMIT_MESSAGE}" && tree ./
- if [[ "${TRAVIS_BRANCH}" == "master" && "${TRAVIS_EVENT_TYPE}" == "push" && "${TRAVIS_REPO_SLUG}" == "xuwei-k/scalaz-docs" ]];
  then git push git@github.com:xuwei-k/scalaz-docs.git gh-pages:gh-pages ; fi
after_script:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
- find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
env:
  global:
  - secure: p1gVVRL+RH4G5ULpgFwavm7hjq1Z6Iir4aYazlr8dWu788e2aAFXGtz6GTBWDLDF/nD3mVtB1ytok8vPILrixu1LowfbpEKi/hQjzxc4cjSgMwzZr+dIOFlKBe4i4APMcx2JYbR4txzDxzdRtAtjy/BsVu+J13HV5qzrvdA4dvdIH/+l+SDQ2VWeCnMI5vjcqAygEIpgCPvbFmdiCRS0ARGl4vCIsMpAI2qMBkPRE+NoYg3axThoCp0rkmyhfvrImZyuX7kzq5RSBZYPzCmeRdcsHBSztffQxEL68bdoVEKe7GBMJCu4vRpF8nBXEsCvQ5yGoocalzSpCoyYibPJTz+f7GfaFSlzf4Vdr1OoYLjxjINSxofzE0QS6PWmJfgQ61gReXkE/bGFt0vDBdDPUQQ+BWLUbKmvEi6IkI1kSF+jqSLYxZQugaI3M67/6MRcBvVQ/h52HLkbBfxbZbX86+5y6EBovWeSnoG+UaYCWAlUxt7Qym3QVaPooCBoOzP40Q+Euq/HX8rgzd1Llw9xN6Vd/JLva2vdNOkkH5d2W8Mabv/88e2iEkiB7I6XQYwTe/7s91lBaeENkNBe5WtZ5Z/h5eZm3AKnNU+RDC6VvItR7WJG7JEbiYBH/TEFR1kZAOBdl+vw82eQgdCJ+i5KpqrjO5HeCeEmv6umW3UVV6I=
